;;; Restaurant example from chapter 18, encoded
;;; using multivalued input attributes suitable for
;;; decision-tree learning.
(define *restaurant-problem*
  (make-learning-problem/default-weights
   '((alternate yes no)
     (bar yes no)
     (fri/sat yes no)
     (hungry yes no)
     (patrons none some full)
     (price D DD DDD)
     (raining yes no)
     (reservation yes no)
     (type french italian thai burger)
     (waitestimate 0 10 30 60))
   '((willwait yes no))
   '(((willwait . yes) (alternate . yes)  (bar . no)  (fri/sat . no)
      (hungry . yes)  (patrons . some)  (price . DDD)  (raining . no)
      (reservation . yes)  (type . french)   (waitestimate . 0)   )
     ((willwait . no) (alternate . yes)  (bar . no)  (fri/sat . no)
      (hungry . yes)  (patrons . full)  (price . D)  (raining . no)
      (reservation . no)  (type . thai)   (waitestimate . 30)   )
     ((willwait . yes) (alternate . no)  (bar . yes)  (fri/sat . no)
      (hungry . no)  (patrons . some)  (price . D)  (raining . no)
      (reservation . no)  (type . burger)   (waitestimate . 0)   )
     ((willwait . yes) (alternate . yes)  (bar . no)  (fri/sat . yes)
      (hungry . yes)  (patrons . full)  (price . D)  (raining . no)
      (reservation . no)  (type . thai)   (waitestimate . 10)   )
     ((willwait . no) (alternate . yes)  (bar . no)  (fri/sat . yes)
      (hungry . no)  (patrons . full)  (price . DDD)  (raining . no)
      (reservation . yes)  (type . french)   (waitestimate . 60)   )
     ((willwait . yes) (alternate . no)  (bar . yes)  (fri/sat . no)
      (hungry . yes)  (patrons . some)  (price . DD)  (raining . yes)
      (reservation . yes)  (type . italian)   (waitestimate . 0)   )
     ((willwait . no) (alternate . no)  (bar . yes)  (fri/sat . no)
      (hungry . no)  (patrons . none)  (price . D)  (raining . yes)
      (reservation . no)  (type . burger)   (waitestimate . 0)   )
     ((willwait . yes) (alternate . no)  (bar . no)  (fri/sat . no)
      (hungry . yes)  (patrons . some)  (price . DD)  (raining . yes)
      (reservation . yes)  (type . thai)   (waitestimate . 0)   )
     ((willwait . no) (alternate . no)  (bar . yes)  (fri/sat . yes)
      (hungry . no)  (patrons . full)  (price . D)  (raining . yes)
      (reservation . no)  (type . burger)   (waitestimate . 60)   )
     ((willwait . no) (alternate . yes)  (bar . yes)  (fri/sat . yes)
      (hungry . yes)  (patrons . full)  (price . DDD)  (raining . no)
      (reservation . yes)  (type . italian)   (waitestimate . 10)   )
     ((willwait . no) (alternate . no)  (bar . no)  (fri/sat . no)
      (hungry . no)  (patrons . none)  (price . D)  (raining . no)
      (reservation . no)  (type . thai)   (waitestimate . 0)   )
     ((willwait . yes) (alternate . yes)  (bar . yes)  (fri/sat . yes)
      (hungry . yes)  (patrons . full)  (price . D)  (raining . no)
      (reservation . no)  (type . burger)   (waitestimate . 30)   ))))
